---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetesmanifest
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: kubernetesmanifest
  targetNamespace: testvote
  timeout: 3m0s
  wait: true
